# Brewfile - Homebrew dependencies

brew "autojump"
brew "bash"
brew "bash-completion"
brew "direnv"
brew "doctl"
brew "gh"
brew "git"
brew "lazygit"
brew "neovim"
brew "rbenv"
brew "ruby-build"
brew "starship"
cask "ghostty"
