#!/usr/bin/env bash

set -e

cd "$HOME"

for link in .gitconfig .gitignore .irbrc .vimrc .zshrc; do
  if [ -L "$HOME/$link" ]; then
    echo "Link '$link' already exists"
  else
    ln -s "$HOME/Code/dottfiles/$link" .
  fi
done
